--
-- PostgreSQL database dump
--

-- Dumped from database version 9.1.9
-- Dumped by pg_dump version 9.2.4
-- Started on 2013-11-04 14:18:16 CET

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = distribution, pg_catalog;

--
-- TOC entry 4134 (class 0 OID 167865)
-- Dependencies: 511
-- Data for Name: installation_treatment; Type: TABLE DATA; Schema: distribution; Owner: sige
--

INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (152, 303, 393.414, false, true, false, true, true, false, false, true, false, 30000.00, NULL, '010100002015550000D6AFAE9B80D920418FD7AC4814EC0141', 'Gonelles', 4005, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (141, 16, 1380.386, false, true, false, false, false, false, false, false, false, NULL, 'Commande pompe Pacoresse : fichier word', '01010000201555000003ED2FBDD32A2141F00C641703E00141', 'Orgevaux', 1025, 1, 1, NULL, NULL, NULL, 1954, NULL, '4500', NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (151, 4, 843.675, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000A380C49BD51521411BCC4F372A9F0141', 'Chamby', 1004, 1, 1, NULL, NULL, NULL, 1912, NULL, '4496', NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (157, 13, 950.519, false, false, false, false, false, false, false, false, false, NULL, 'Fermeture: clé SIGEChloration sur arrivée de Remaufens', '010100002015550000594B2215DCE22041321EC6E8791F0241', 'Maison Jean', 1018, 1, 1, NULL, NULL, NULL, 1964, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (156, 13, 950.519, false, false, false, false, false, false, false, false, false, NULL, 'Fermeture: clé SIGEChloration sur départ vers Sommet', '010100002015550000594B2215DCE22041321EC6E8791F0241', 'Maison Jean', 1018, 1, 1, NULL, NULL, NULL, 1964, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (148, 17, 1257.999, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000EA49D38DAB26214107580E1954C90141', 'Pacoresse', 1026, 1, 1, NULL, NULL, NULL, 1973, NULL, '4500', '6647');
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (155, 18, 654.509, true, false, false, false, false, false, false, false, false, NULL, NULL, '0101000020155500001A1131C840DD20418C8BDD050C050241', 'Panessière', 1027, 1, 1, NULL, NULL, NULL, 1985, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (145, 25, 584.798, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000EF9516D168172141A164722AB87A0141', 'Sous-Sonzier', 1036, 1, 1, NULL, NULL, NULL, 1936, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (146, 121, 743.718, true, false, false, false, false, false, false, false, false, 2500.00, NULL, '010100002015550000FAE837829E252141E3A51F455E930141', 'Cheset', 2016, 1, 1, NULL, NULL, NULL, 1894, NULL, '4832', NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (147, 163, 1470.479, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000E2964DEC083621414B764BFE0BE70141', 'Soladier', 2075, 1, 1, NULL, NULL, NULL, 1942, NULL, '4500', NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (143, 164, 1263.423, true, false, false, false, false, false, false, false, false, 50.00, 'clé SIGE_ accès hivernal difficile', '0101000020155500000954BDB01E292141F8D4DA01DA2A0141', 'Sonchaux', 2076, 1, 1, NULL, NULL, NULL, 1957, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (142, 461, 1166.658, false, true, false, false, false, false, false, false, false, NULL, 'nettoyer Chollet et Dufaux pendant mise HS de Jor', '0101000020155500002050EC4791312141FEF6AF138DB50141', 'Jor', 3063, 1, 1, NULL, NULL, NULL, 1899, NULL, '4500', '3331');
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (134, 427, 1531.229, false, true, false, false, false, false, false, false, false, NULL, 'Local de chloration', '01010000201555000011E79F38CD3221410A6A74DEA1710141', 'Chamossale', 3022, 1, 1, NULL, NULL, NULL, 1899, NULL, '6200', '6731');
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (135, 494, 1260.063, false, true, false, false, false, false, false, false, false, NULL, NULL, '0101000020155500003E0F07BE05342141A49321FE42970141', 'Preisaz', 3100, 1, 1, NULL, NULL, NULL, 1899, NULL, '6200', '9248');
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (136, 534, 921.364, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000E781B82C12292141CD8AD18887590141', 'Massillon', 3070, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (150, 402, 1032.491, false, true, false, false, false, false, false, false, false, NULL, 'Rénovée en  1888 / 1942 / 1991 Chloration et pompageChloration sur départ vers Glion', '010100002015550000C6F321AB9C292141E677DC20A5AB0141', 'Avants', 3002, 1, 1, NULL, NULL, NULL, 1868, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (149, 402, 1032.491, false, false, true, false, false, false, false, false, false, NULL, 'Rénovée en  1888 / 1942 / 1991 Chloration et pompageChloration sur départ vers Sollard', '010100002015550000C6F321AB9C292141E677DC20A5AB0141', 'Avants', 3002, 1, 1, NULL, NULL, NULL, 1868, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (137, 469, 607.461, false, true, false, false, false, false, false, false, false, NULL, 'Incertains: nb de captages (1 ou 4) + dét des zones de prot. / Fermeture: clé SIGE', '010100002015550000075FB92E8C002141A2442A8823410241', 'Moille Saulaz', 3071, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (138, 436, 527.622, false, false, true, false, false, false, false, false, false, NULL, 'Rénovée en: 1959, 1996', '010100002015550000CBB9771FB02021417E83FEE302170141', 'Confin du Renard', 3032, 1, 1, NULL, NULL, NULL, 1912, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (139, 410, 860.383, true, false, false, false, false, false, false, false, false, 400.00, 'Autre fonction: pompage', '0101000020155500002183CBE1E201214125C5F09E0F720241', 'Baumettaz', 3007, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (140, 589, 472.759, true, false, false, false, false, false, false, false, false, 1000.00, NULL, '010100002015550000C4480633381E2141A2D6F25AF4430141', 'Veytaux', 3122, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (154, 562, 500.420, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000F6F553BCDAEB20410C925F33DDFB0141', 'St-Pierre', 4009, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (153, 562, 500.420, false, true, false, false, false, false, false, false, false, NULL, NULL, '010100002015550000F6F553BCDAEB20410C925F33DDFB0141', 'St-Pierre', 4009, 1, 1, NULL, NULL, NULL, 1899, NULL, NULL, NULL);
INSERT INTO distribution.installation_treatment (id, id_installation, altitude, sanitization_uv, sanitization_chlorine_liquid, sanitization_chlorine_gazeous, sanitization_ozone, filtration_membrane, filtration_sandorgravel, flocculation, activatedcharcoal, settling, treatment_capacity, remarks, geometry, name, identification, id_status, id_distributor, id_remote, view_schema, links, year, open_water_surface, parcel, eca) VALUES (144, 563, 1520.000, false, false, false, false, true, false, true, false, false, 400.00, NULL, '01010000201555000049FFC37EE4392141C17242906AA30141', 'Jaman', 3060, 6, 1, NULL, NULL, NULL, 1899, NULL, '6200', NULL);


--
-- TOC entry 4139 (class 0 OID 0)
-- Dependencies: 510
-- Name: installation_treatment_id_seq; Type: SEQUENCE SET; Schema: distribution; Owner: sige
--

SELECT pg_catalog.setval('installation_treatment_id_seq', 157, true);


-- Completed on 2013-11-04 14:18:16 CET

--
-- PostgreSQL database dump complete
--

