# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pipeSearch.ui'
#
# Created: Wed Jan 18 10:59:32 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pipeSearch(object):
    def setupUi(self, pipeSearch):
        pipeSearch.setObjectName(_fromUtf8("pipeSearch"))
        pipeSearch.resize(270, 321)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pipeSearch.sizePolicy().hasHeightForWidth())
        pipeSearch.setSizePolicy(sizePolicy)
        pipeSearch.setWindowTitle(QtGui.QApplication.translate("pipeSearch", "qWat :: pipe search", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(pipeSearch)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.searchTabWidget = QtGui.QTabWidget(pipeSearch)
        self.searchTabWidget.setObjectName(_fromUtf8("searchTabWidget"))
        self.geomTab = QtGui.QWidget()
        self.geomTab.setObjectName(_fromUtf8("geomTab"))
        self.geomLengthWidget = QtGui.QWidget(self.geomTab)
        self.geomLengthWidget.setGeometry(QtCore.QRect(10, 20, 262, 45))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomLengthWidget.sizePolicy().hasHeightForWidth())
        self.geomLengthWidget.setSizePolicy(sizePolicy)
        self.geomLengthWidget.setObjectName(_fromUtf8("geomLengthWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.geomLengthWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.geomLengthCheck = QtGui.QCheckBox(self.geomLengthWidget)
        self.geomLengthCheck.setText(QtGui.QApplication.translate("pipeSearch", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.geomLengthCheck.setObjectName(_fromUtf8("geomLengthCheck"))
        self.horizontalLayout.addWidget(self.geomLengthCheck)
        self.geomLengthModeCombo = QtGui.QComboBox(self.geomLengthWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomLengthModeCombo.sizePolicy().hasHeightForWidth())
        self.geomLengthModeCombo.setSizePolicy(sizePolicy)
        self.geomLengthModeCombo.setAccessibleDescription(_fromUtf8(""))
        self.geomLengthModeCombo.setObjectName(_fromUtf8("geomLengthModeCombo"))
        self.geomLengthModeCombo.addItem(_fromUtf8(""))
        self.geomLengthModeCombo.setItemText(0, _fromUtf8("<"))
        self.geomLengthModeCombo.addItem(_fromUtf8(""))
        self.geomLengthModeCombo.setItemText(1, QtGui.QApplication.translate("pipeSearch", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout.addWidget(self.geomLengthModeCombo)
        self.geomLengthValueSpin = QtGui.QDoubleSpinBox(self.geomLengthWidget)
        self.geomLengthValueSpin.setAccessibleDescription(_fromUtf8(""))
        self.geomLengthValueSpin.setSpecialValueText(_fromUtf8(""))
        self.geomLengthValueSpin.setDecimals(1)
        self.geomLengthValueSpin.setMaximum(99999.0)
        self.geomLengthValueSpin.setProperty("value", 3.0)
        self.geomLengthValueSpin.setObjectName(_fromUtf8("geomLengthValueSpin"))
        self.horizontalLayout.addWidget(self.geomLengthValueSpin)
        self.searchTabWidget.addTab(self.geomTab, _fromUtf8(""))
        self.schemaTab = QtGui.QWidget()
        self.schemaTab.setObjectName(_fromUtf8("schemaTab"))
        self.formLayout = QtGui.QFormLayout(self.schemaTab)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.schemaParentCombo = QtGui.QComboBox(self.schemaTab)
        self.schemaParentCombo.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.schemaParentCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.schemaParentCombo.setObjectName(_fromUtf8("schemaParentCombo"))
        self.schemaParentCombo.addItem(_fromUtf8(""))
        self.schemaParentCombo.setItemText(0, QtGui.QApplication.translate("pipeSearch", "has a parent", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaParentCombo.addItem(_fromUtf8(""))
        self.schemaParentCombo.setItemText(1, QtGui.QApplication.translate("pipeSearch", "has no parent", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.schemaParentCombo)
        self.schemaFunctionCombo = QtGui.QComboBox(self.schemaTab)
        self.schemaFunctionCombo.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.schemaFunctionCombo.setToolTip(QtGui.QApplication.translate("pipeSearch", "Select pipes against their function properties: if the function is visible or not in the schematic view.", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaFunctionCombo.setObjectName(_fromUtf8("schemaFunctionCombo"))
        self.schemaFunctionCombo.addItem(_fromUtf8(""))
        self.schemaFunctionCombo.setItemText(0, QtGui.QApplication.translate("pipeSearch", "visible", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaFunctionCombo.addItem(_fromUtf8(""))
        self.schemaFunctionCombo.setItemText(1, QtGui.QApplication.translate("pipeSearch", "invisible", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.schemaFunctionCombo)
        self.schemaForceCombo = QtGui.QComboBox(self.schemaTab)
        self.schemaForceCombo.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.schemaForceCombo.setToolTip(QtGui.QApplication.translate("pipeSearch", "Force view allow to override the function attribute for schematic view. Auto is the defalut pipe behavior.", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaForceCombo.setObjectName(_fromUtf8("schemaForceCombo"))
        self.schemaForceCombo.addItem(_fromUtf8(""))
        self.schemaForceCombo.setItemText(0, QtGui.QApplication.translate("pipeSearch", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaForceCombo.addItem(_fromUtf8(""))
        self.schemaForceCombo.setItemText(1, QtGui.QApplication.translate("pipeSearch", "visible", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaForceCombo.addItem(_fromUtf8(""))
        self.schemaForceCombo.setItemText(2, QtGui.QApplication.translate("pipeSearch", "invisible", None, QtGui.QApplication.UnicodeUTF8))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.schemaForceCombo)
        self.schemaFunctionCheck = QtGui.QCheckBox(self.schemaTab)
        self.schemaFunctionCheck.setText(QtGui.QApplication.translate("pipeSearch", "Function", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaFunctionCheck.setObjectName(_fromUtf8("schemaFunctionCheck"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.schemaFunctionCheck)
        self.schemaParentCheck = QtGui.QCheckBox(self.schemaTab)
        self.schemaParentCheck.setAutoFillBackground(False)
        self.schemaParentCheck.setText(QtGui.QApplication.translate("pipeSearch", "Pipe", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaParentCheck.setTristate(False)
        self.schemaParentCheck.setObjectName(_fromUtf8("schemaParentCheck"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.schemaParentCheck)
        self.schemaForceCheck = QtGui.QCheckBox(self.schemaTab)
        self.schemaForceCheck.setText(QtGui.QApplication.translate("pipeSearch", "Force view", None, QtGui.QApplication.UnicodeUTF8))
        self.schemaForceCheck.setObjectName(_fromUtf8("schemaForceCheck"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.schemaForceCheck)
        self.searchTabWidget.addTab(self.schemaTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.searchTabWidget, 0, 0, 1, 2)
        self.searchButton = QtGui.QPushButton(pipeSearch)
        self.searchButton.setText(QtGui.QApplication.translate("pipeSearch", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.gridLayout.addWidget(self.searchButton, 1, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(pipeSearch)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 2)
        self.cancelButton = QtGui.QPushButton(pipeSearch)
        self.cancelButton.setText(QtGui.QApplication.translate("pipeSearch", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout.addWidget(self.cancelButton, 3, 0, 1, 1)
        self.selectButton = QtGui.QPushButton(pipeSearch)
        self.selectButton.setEnabled(False)
        self.selectButton.setText(QtGui.QApplication.translate("pipeSearch", "Select elements", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton.setObjectName(_fromUtf8("selectButton"))
        self.gridLayout.addWidget(self.selectButton, 3, 1, 1, 1)

        self.retranslateUi(pipeSearch)
        self.searchTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pipeSearch)

    def retranslateUi(self, pipeSearch):
        self.searchTabWidget.setTabText(self.searchTabWidget.indexOf(self.geomTab), QtGui.QApplication.translate("pipeSearch", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTabWidget.setTabText(self.searchTabWidget.indexOf(self.schemaTab), QtGui.QApplication.translate("pipeSearch", "Schematic", None, QtGui.QApplication.UnicodeUTF8))

