/*
	qWat - QGIS Water Module

	SQL file :: vl_pipe_material table
*/


DROP TABLE IF EXISTS distribution.vl_pipe_material CASCADE;
CREATE TABLE distribution.vl_pipe_material ( id SERIAL, CONSTRAINT "vl_pipe_material_pk" PRIMARY KEY (id) );
COMMENT ON TABLE distribution.vl_pipe_material IS 'List of materials for pipe. All the possible combinations material/diameter are listed in this table. _displayname_fr is automatically generated by rules on insert and update. It is meant to be used in QGIS for the combo box of pipe.id_material';


/* COLUMNS*/
ALTER TABLE distribution.vl_pipe_material ADD COLUMN short_fr varchar(8);
ALTER TABLE distribution.vl_pipe_material ADD COLUMN value_fr varchar(30);
ALTER TABLE distribution.vl_pipe_material ADD COLUMN _displayname_fr varchar(18); /* created automatically, used for display only*/
ALTER TABLE distribution.vl_pipe_material ADD COLUMN short_en varchar(8);
ALTER TABLE distribution.vl_pipe_material ADD COLUMN value_en varchar(30);
ALTER TABLE distribution.vl_pipe_material ADD COLUMN _displayname_en varchar(18); /* created automatically, used for display only*/

ALTER TABLE distribution.vl_pipe_material ADD COLUMN diameter varchar(10); /* need to be varchar to specify a string for unknown or inches with a "*/
ALTER TABLE distribution.vl_pipe_material ADD COLUMN diameter_internal decimal(7,3);
ALTER TABLE distribution.vl_pipe_material ADD COLUMN diameter_external decimal(7,3);

ALTER TABLE distribution.vl_pipe_material ADD COLUMN code_sire smallint;

/* TRIGGER */
CREATE OR REPLACE FUNCTION distribution.vl_pipe_material_displayname_fr() RETURNS trigger AS 
$BODY$
	BEGIN
		 UPDATE distribution.vl_pipe_material SET 
		 _displayname_en = NEW.short_en||' '||NEW.diameter,
		 _displayname_fr = NEW.short_fr||' '||NEW.diameter 
		 WHERE id = NEW.id ;
		 RETURN NEW;
	END;
$BODY$ LANGUAGE 'plpgsql';
COMMENT ON FUNCTION distribution.vl_pipe_material_displayname_fr() IS 'Fcn/Trigger: updates the fancy value_fr in the material table.';

CREATE TRIGGER fancy_value_fr_trigger
	AFTER INSERT OR UPDATE OF short_fr, diameter ON distribution.vl_pipe_material
	FOR EACH ROW
	EXECUTE PROCEDURE distribution.vl_pipe_material_displayname_fr();
COMMENT ON TRIGGER fancy_value_fr_trigger ON distribution.vl_pipe_material IS 'Trigger: updates the fancy value_fr in the material table.';


/* Predefined functions list */
/* This has to be filled by user to fullfile language preferences */
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('Inconnu','Inconnu'            ,''       , NULL   , NULL, 1 );
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,''       , NULL   , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'100'    ,100     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'120'    ,120     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'125'    ,125     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'150'    ,150     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'175'    ,175     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'180'    ,180     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'200'    ,200     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'250'    ,250     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'300'    ,300     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'400'    ,400     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'50'     ,50      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'500'    ,500     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'60'     ,60      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'600'    ,600     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'65'     ,65      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'70'     ,70      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'75'     ,75      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'80'     ,80      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('AC'  ,'Acier'                 ,'800'    ,800     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,''       , NULL   , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'0.5"'   ,16      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'0.75"'  ,21.6    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'1 '     ,27.2    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'1"'     ,27.2    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'100'    ,105.3   , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'1.25"'  ,35.9    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'1.5"'   ,41.8    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'2"'     ,53      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'2.5"'   ,68.8    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'3"'     ,80.8    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'4"'     ,105.3   , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACG' ,'Acier galvanisé'       ,'80'     ,80.8    , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACI' ,'Acier inoxydable'      ,'100'    ,100     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACI' ,'Acier inoxydable'      ,'125'    ,125     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACI' ,'Acier inoxydable'      ,'150'    ,150     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACI' ,'Acier inoxydable'      ,'200'    ,200     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACI' ,'Acier inoxydable'      ,'250'    ,250     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,''       , NULL   , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'100'    ,100     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'125'    ,125     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'150'    ,150     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'200'    ,200     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'300'    ,300     , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'50'     ,50      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'60'     ,60      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('ACPR','Acier prestolic'       ,'80'     ,80      , NULL, 11);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,''       , NULL   , NULL, 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'1"'     ,25      ,28   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'10'     ,10      ,12   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'12'     ,10      ,12   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'1.25"'  ,32      ,35   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'15'     ,13      ,15   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'17'     ,16      ,18   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'22/19'  ,20      ,22   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'25'     ,25      ,28   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('CU'  ,'Cuivre'                ,'32'     ,32      ,35   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,''       , NULL   , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'100'    ,100     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'110'    ,110     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'120'    ,120     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'125'    ,125     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'150'    ,150     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'175'    ,175     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'180'    ,180     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'200'    ,200     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'250'    ,250     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'300'    ,300     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'350'    ,350     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'375'    ,375     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'400'    ,400     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'50'     ,50      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'500'    ,500     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'60'     ,60      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'600'    ,600     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'65'     ,65      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'70'     ,70      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'80'     ,80      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'800'    ,800     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('F'   ,'Fonte'                 ,'90'     ,90      , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'100'    ,100     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'125'    ,125     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'150'    ,150     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'200'    ,200     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'250'    ,250     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'300'    ,300     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('FAE' ,'Fonte auto-étanche'    ,'400'    ,400     , NULL, 4);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,''       , NULL   , NULL, 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'100'    , NULL   , NULL, 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'110'    ,90      ,110  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'125'    ,102.2   ,125  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'150'    , NULL   , NULL, 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'160'    ,130.8   ,160  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'200'    ,163.6   ,200  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'25'     ,20.4    ,25   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'250'    ,204.6   ,250  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'32'     ,26.2    ,32   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'355'    ,290.4   ,355  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'40'     ,32.6    ,40   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'400'    ,327.2   ,400  , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'50'     ,40.8    ,50   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'63'     ,51.4    ,63   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'75'     ,61.4    ,75   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE'  ,'Polyéthylène'          ,'90'     ,73.6    ,90   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE80','Polyéthylène 80'       ,'50'     , NULL   , NULL, 8);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PE80','Polyéthylène 80'       ,'63'     , NULL   , NULL, 8);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PEX' ,'Polyéthylène réticulé' ,'63'     ,50      ,63   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PEX' ,'Polyéthylène réticulé' ,'90'     ,75      ,90   , 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PEX' ,'Polyéthylène réticulé' ,'160'    , NULL   , NULL, 10);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,''       , NULL   , NULL, 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'0.2'    , NULL   , NULL, 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'0.75"'  ,20.4    ,25   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'1"'     ,32.6    ,40   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'1.25"'  ,40.8    ,50   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'1.5"'   ,51.4    ,63   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'2"'     ,61.4    ,75   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'20'     ,16      ,20   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'25'     ,20.4    ,25   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'2.5"'   ,73.6    ,90   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'32'     ,26.2    ,32   , 0);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PL'  ,'Plastique'             ,'150'    , NULL   , NULL, 0);        /*SHOULD BE REMOVED */
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','100'    , NULL   , NULL, 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','120'    , NULL   , NULL, 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','125'    , NULL   , NULL, 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','140'    ,125     ,140  , 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','150'    , NULL   , NULL, 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','160'    ,150     ,160  , 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','20'     ,15.4    ,20   , 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','250'    ,225     ,250  , 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','600'    , NULL   , NULL, 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('PVC' ,'Chlorure de polyvinyle','75'     ,65      ,75   , 6);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'100'    ,80      , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'120'    ,100     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'125'    ,100     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'150'    ,125     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'160'    ,125     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'175'    ,150     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'20'     , NULL   , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'200'    ,175     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'250'    ,200     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'30'     , NULL   , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'300'    ,250     , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'50'     ,50      , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TAC' ,'Amiante Ciment'        ,'80'     ,60      , NULL, 2);
INSERT INTO distribution.vl_pipe_material (short_fr,value_fr,diameter,diameter_internal,diameter_external,code_sire) VALUES ('TC'  ,'Tuyau Ciment'          ,'20'     , NULL   , NULL, 3);


