# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qwat.ui'
#
# Created: Tue Aug 20 15:24:34 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_qwat(object):
    def setupUi(self, qwat):
        qwat.setObjectName(_fromUtf8("qwat"))
        qwat.resize(634, 686)
        self.gridLayout = QtGui.QGridLayout(qwat)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(qwat)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 3)
        self.rubberColor = QtGui.QLabel(qwat)
        self.rubberColor.setText(_fromUtf8(""))
        self.rubberColor.setObjectName(_fromUtf8("rubberColor"))
        self.gridLayout.addWidget(self.rubberColor, 0, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(qwat)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.nodeTab = QtGui.QWidget()
        self.nodeTab.setObjectName(_fromUtf8("nodeTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.nodeTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.nodeUnusedFrame = QtGui.QFrame(self.nodeTab)
        self.nodeUnusedFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nodeUnusedFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nodeUnusedFrame.setObjectName(_fromUtf8("nodeUnusedFrame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.nodeUnusedFrame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.nodeUnusedFrame)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.nodeUnusedProgressBar = QtGui.QProgressBar(self.nodeUnusedFrame)
        self.nodeUnusedProgressBar.setProperty("value", 0)
        self.nodeUnusedProgressBar.setObjectName(_fromUtf8("nodeUnusedProgressBar"))
        self.gridLayout_5.addWidget(self.nodeUnusedProgressBar, 1, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.nodeUnusedFrame)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.nodeUnusedFrame, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 9, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 0, 1, 1)
        self.nodeTypeFrame = QtGui.QFrame(self.nodeTab)
        self.nodeTypeFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nodeTypeFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nodeTypeFrame.setObjectName(_fromUtf8("nodeTypeFrame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.nodeTypeFrame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.nodeTypeProgressBar = QtGui.QProgressBar(self.nodeTypeFrame)
        self.nodeTypeProgressBar.setProperty("value", 0)
        self.nodeTypeProgressBar.setObjectName(_fromUtf8("nodeTypeProgressBar"))
        self.gridLayout_6.addWidget(self.nodeTypeProgressBar, 1, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.nodeTypeFrame)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.nodeTypeFrame)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.nodeTypeFrame, 6, 0, 1, 1)
        self.nodeErrorFrame = QtGui.QFrame(self.nodeTab)
        self.nodeErrorFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.nodeErrorFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.nodeErrorFrame.setObjectName(_fromUtf8("nodeErrorFrame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.nodeErrorFrame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.errorsWidget = QtGui.QWidget(self.nodeErrorFrame)
        self.errorsWidget.setObjectName(_fromUtf8("errorsWidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.errorsWidget)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.nodeErrorTooCloseProgressBar = QtGui.QProgressBar(self.errorsWidget)
        self.nodeErrorTooCloseProgressBar.setProperty("value", 0)
        self.nodeErrorTooCloseProgressBar.setObjectName(_fromUtf8("nodeErrorTooCloseProgressBar"))
        self.gridLayout_8.addWidget(self.nodeErrorTooCloseProgressBar, 4, 1, 1, 1)
        self.nodeErrorNoPipeOrValveProgressBar = QtGui.QProgressBar(self.errorsWidget)
        self.nodeErrorNoPipeOrValveProgressBar.setProperty("value", 0)
        self.nodeErrorNoPipeOrValveProgressBar.setObjectName(_fromUtf8("nodeErrorNoPipeOrValveProgressBar"))
        self.gridLayout_8.addWidget(self.nodeErrorNoPipeOrValveProgressBar, 2, 1, 1, 1)
        self.nodeErrorUndefTypeButton = QtGui.QPushButton(self.errorsWidget)
        self.nodeErrorUndefTypeButton.setObjectName(_fromUtf8("nodeErrorUndefTypeButton"))
        self.gridLayout_8.addWidget(self.nodeErrorUndefTypeButton, 0, 3, 1, 1)
        self.line = QtGui.QFrame(self.errorsWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 4)
        self.nodeErrorUndefTypeProgressBar = QtGui.QProgressBar(self.errorsWidget)
        self.nodeErrorUndefTypeProgressBar.setProperty("value", 0)
        self.nodeErrorUndefTypeProgressBar.setObjectName(_fromUtf8("nodeErrorUndefTypeProgressBar"))
        self.gridLayout_8.addWidget(self.nodeErrorUndefTypeProgressBar, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.errorsWidget)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_8.addWidget(self.label_10, 6, 0, 1, 1)
        self.nodeErrorNoHeightProgressBar = QtGui.QProgressBar(self.errorsWidget)
        self.nodeErrorNoHeightProgressBar.setProperty("value", 0)
        self.nodeErrorNoHeightProgressBar.setObjectName(_fromUtf8("nodeErrorNoHeightProgressBar"))
        self.gridLayout_8.addWidget(self.nodeErrorNoHeightProgressBar, 6, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.errorsWidget)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 4, 0, 1, 1)
        self.nodeErrorUndefTypeCount = QtGui.QLabel(self.errorsWidget)
        self.nodeErrorUndefTypeCount.setObjectName(_fromUtf8("nodeErrorUndefTypeCount"))
        self.gridLayout_8.addWidget(self.nodeErrorUndefTypeCount, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.errorsWidget)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.errorsWidget)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_8.addWidget(self.label_12, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.errorsWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_8.addWidget(self.line_2, 3, 0, 1, 4)
        self.line_3 = QtGui.QFrame(self.errorsWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_8.addWidget(self.line_3, 5, 0, 1, 4)
        self.nodeErrorNoPipeOrValveCount = QtGui.QLabel(self.errorsWidget)
        self.nodeErrorNoPipeOrValveCount.setObjectName(_fromUtf8("nodeErrorNoPipeOrValveCount"))
        self.gridLayout_8.addWidget(self.nodeErrorNoPipeOrValveCount, 2, 2, 1, 1)
        self.nodeErrorTooCloseCount = QtGui.QLabel(self.errorsWidget)
        self.nodeErrorTooCloseCount.setObjectName(_fromUtf8("nodeErrorTooCloseCount"))
        self.gridLayout_8.addWidget(self.nodeErrorTooCloseCount, 4, 2, 1, 1)
        self.nodeErrorNoHeightCount = QtGui.QLabel(self.errorsWidget)
        self.nodeErrorNoHeightCount.setObjectName(_fromUtf8("nodeErrorNoHeightCount"))
        self.gridLayout_8.addWidget(self.nodeErrorNoHeightCount, 6, 2, 1, 1)
        self.nodeErrorNoPipeOrValveButton = QtGui.QPushButton(self.errorsWidget)
        self.nodeErrorNoPipeOrValveButton.setObjectName(_fromUtf8("nodeErrorNoPipeOrValveButton"))
        self.gridLayout_8.addWidget(self.nodeErrorNoPipeOrValveButton, 2, 3, 1, 1)
        self.nodeErrorTooCloseButton = QtGui.QPushButton(self.errorsWidget)
        self.nodeErrorTooCloseButton.setObjectName(_fromUtf8("nodeErrorTooCloseButton"))
        self.gridLayout_8.addWidget(self.nodeErrorTooCloseButton, 4, 3, 1, 1)
        self.nodeErrorNoHeightButton = QtGui.QPushButton(self.errorsWidget)
        self.nodeErrorNoHeightButton.setObjectName(_fromUtf8("nodeErrorNoHeightButton"))
        self.gridLayout_8.addWidget(self.nodeErrorNoHeightButton, 6, 3, 1, 1)
        self.gridLayout_7.addWidget(self.errorsWidget, 2, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.nodeErrorFrame)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.nodeErrorFrame, 8, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(481, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 3, 0, 1, 1)
        self.widget = QtGui.QWidget(self.nodeTab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.applyToCombo = QtGui.QComboBox(self.widget)
        self.applyToCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.applyToCombo.setObjectName(_fromUtf8("applyToCombo"))
        self.applyToCombo.addItem(_fromUtf8(""))
        self.applyToCombo.addItem(_fromUtf8(""))
        self.applyToCombo.addItem(_fromUtf8(""))
        self.applyToCombo.addItem(_fromUtf8(""))
        self.applyToCombo.setItemText(3, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.applyToCombo, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 2, 2)
        self.nodeStartButton = QtGui.QPushButton(self.widget)
        self.nodeStartButton.setObjectName(_fromUtf8("nodeStartButton"))
        self.gridLayout_3.addWidget(self.nodeStartButton, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 1, 0, 1, 1)
        self.nodeInfoLabel = QtGui.QLabel(self.nodeTab)
        self.nodeInfoLabel.setObjectName(_fromUtf8("nodeInfoLabel"))
        self.gridLayout_4.addWidget(self.nodeInfoLabel, 2, 0, 1, 1)
        self.tabWidget.addTab(self.nodeTab, _fromUtf8(""))
        self.valveTab = QtGui.QWidget()
        self.valveTab.setObjectName(_fromUtf8("valveTab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.valveTab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.valveClosePipesStartButton = QtGui.QPushButton(self.valveTab)
        self.valveClosePipesStartButton.setObjectName(_fromUtf8("valveClosePipesStartButton"))
        self.gridLayout_9.addWidget(self.valveClosePipesStartButton, 0, 0, 1, 1)
        self.valveClosePipesProgressBar = QtGui.QProgressBar(self.valveTab)
        self.valveClosePipesProgressBar.setProperty("value", 0)
        self.valveClosePipesProgressBar.setObjectName(_fromUtf8("valveClosePipesProgressBar"))
        self.gridLayout_9.addWidget(self.valveClosePipesProgressBar, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem6, 1, 0, 1, 1)
        self.valveClosePipesStopButton = QtGui.QPushButton(self.valveTab)
        self.valveClosePipesStopButton.setObjectName(_fromUtf8("valveClosePipesStopButton"))
        self.gridLayout_9.addWidget(self.valveClosePipesStopButton, 0, 1, 1, 1)
        self.tabWidget.addTab(self.valveTab, _fromUtf8(""))
        self.schemaTab = QtGui.QWidget()
        self.schemaTab.setObjectName(_fromUtf8("schemaTab"))
        self.tabWidget.addTab(self.schemaTab, _fromUtf8(""))
        self.layerTab = QtGui.QWidget()
        self.layerTab.setObjectName(_fromUtf8("layerTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layerTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layerTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layerTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.nodeLayer = QtGui.QComboBox(self.layerTab)
        self.nodeLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.nodeLayer.setObjectName(_fromUtf8("nodeLayer"))
        self.gridLayout_2.addWidget(self.nodeLayer, 2, 1, 1, 1)
        self.valveLayer = QtGui.QComboBox(self.layerTab)
        self.valveLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.valveLayer.setObjectName(_fromUtf8("valveLayer"))
        self.gridLayout_2.addWidget(self.valveLayer, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.layerTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pipeLayer = QtGui.QComboBox(self.layerTab)
        self.pipeLayer.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.pipeLayer.setObjectName(_fromUtf8("pipeLayer"))
        self.gridLayout_2.addWidget(self.pipeLayer, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 3, 1, 1, 1)
        self.tabWidget.addTab(self.layerTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(qwat)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), qwat.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), qwat.reject)
        QtCore.QMetaObject.connectSlotsByName(qwat)

    def retranslateUi(self, qwat):
        qwat.setWindowTitle(QtGui.QApplication.translate("qwat", "qWat :: configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("qwat", "Delete unused nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("qwat", "Reset nodes type", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorUndefTypeButton.setText(QtGui.QApplication.translate("qwat", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("qwat", "Without height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("qwat", "Too close ", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorUndefTypeCount.setText(QtGui.QApplication.translate("qwat", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("qwat", "Undefinied type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("qwat", "Without pipe or valve", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorNoPipeOrValveCount.setText(QtGui.QApplication.translate("qwat", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorTooCloseCount.setText(QtGui.QApplication.translate("qwat", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorNoHeightCount.setText(QtGui.QApplication.translate("qwat", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorNoPipeOrValveButton.setText(QtGui.QApplication.translate("qwat", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorTooCloseButton.setText(QtGui.QApplication.translate("qwat", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeErrorNoHeightButton.setText(QtGui.QApplication.translate("qwat", "select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("qwat", "Detect erros", None, QtGui.QApplication.UnicodeUTF8))
        self.applyToCombo.setItemText(0, QtGui.QApplication.translate("qwat", "all nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.applyToCombo.setItemText(1, QtGui.QApplication.translate("qwat", "selected nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.applyToCombo.setItemText(2, QtGui.QApplication.translate("qwat", "visible nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("qwat", "Apply to", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeStartButton.setText(QtGui.QApplication.translate("qwat", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeInfoLabel.setText(QtGui.QApplication.translate("qwat", "infoLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nodeTab), QtGui.QApplication.translate("qwat", "Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.valveClosePipesStartButton.setText(QtGui.QApplication.translate("qwat", "close pipes", None, QtGui.QApplication.UnicodeUTF8))
        self.valveClosePipesStopButton.setText(QtGui.QApplication.translate("qwat", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.valveTab), QtGui.QApplication.translate("qwat", "Valves", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.schemaTab), QtGui.QApplication.translate("qwat", "Schematic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("qwat", "Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("qwat", "Valves", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("qwat", "Pipes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.layerTab), QtGui.QApplication.translate("qwat", "Settings", None, QtGui.QApplication.UnicodeUTF8))

